version: "3"
services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
    ports:
      - "8000:8000"
    networks:
      - template
    env_file:
      - ./apps/api-gateway/.env

  auth:
    container_name: auth
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
    ports:
      - "3002:3002"
    networks:
      - template
    env_file:
      - ./apps/auth/.env

  delivery:
    container_name: delivery
    build:
      context: .
      dockerfile: ./apps/delivery/Dockerfile
    ports:
      - "3001:3001"
    networks:
      - template
    env_file:
      - ./apps/delivery/.env


networks:
  template:
