/**
 * Configuration variables required for application. Retrieved from configuration
 * service
 */
export enum RequiredVariables {
  ACCESS_TOKEN_EXPIRE_TIME = 'ACCESS_TOKEN_EXPIRE_TIME',
  REFRESH_TOKEN_EXPIRE_TIME = 'REFRESH_TOKEN_EXPIRE_TIME',
  REFRESH_SECRET = 'REFRESH_SECRET',
  ACCESS_SECRET = 'ACCESS_SECRET',

  DATABASE_URL = 'DATABASE_URL',

  USERMANAGEMENT_MS_HOST = 'USERMANAGEMENT_MS_HOST',
  USERMANAGEMENT_MS_PORT = 'USERMANAGEMENT_MS_PORT',

  DELIVERY_MS_HOST = 'DELIVERY_MS_HOST',
  DELIVERY_MS_PORT = 'DELIVERY_MS_PORT',

  GOOGLE_CLIENT_ID = 'GOOGLE_CLIENT_ID',
  GOOGLE_CLIENT_SECRET = 'GOOGLE_CLIENT_SECRET',

  FACEBOOK_APP_ID = 'FACEBOOK_APP_ID',
  FACEBOOK_APP_SECRET = 'FACEBOOK_APP_SECRET',

  AUTH_SESSION_EXPIRE_TIME = 'AUTH_SESSION_EXPIRE_TIME',
}
